# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
plugin 'cocoapods-flutter'

# 开启module
use_frameworks! linkage: :static # 将组件已静态库的方式引入，使用后，会强制 use_modular_headers
use_modular_headers!

install! 'cocoapods',
         deterministic_uuids: false,
         lock_pod_sources: false,
         disable_input_output_paths: true,
         generate_multiple_pod_projects: true, # 为每一个组件生成一个xcodeproj
         warn_for_unused_master_specs_repo: false,
         preserve_pod_file_structure: true # 保持目录结构不变

pre_install do |_installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

# pod install中间进行hook
post_install do |installer|
  # 设置默认配置
  installer.pods_project.targets.each do |target|
    # puts target.name
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end

  # 通过脚本的方式，设置组件间的链接路径
  aggregate_target = installer.aggregate_targets[0]
  aggregate_build_settings_by_config = aggregate_target.xcconfigs.collect { |k, v| [k, v.to_hash] }.to_h
  # puts aggregate_build_settings_by_config
  installer.pod_target_subprojects.each do |pod_subproject|
    pod_subproject.native_targets.each do |pod_native_target|
      # puts pod_native_target
      pod_native_target.build_configurations.each do |build_configuration|
        aggregate_build_settings = aggregate_build_settings_by_config[build_configuration.name]
        build_configuration.build_settings['HEADER_SEARCH_PATHS'] = "${PODS_ROOT}/Headers/Public"
        build_configuration.build_settings['FRAMEWORK_SEARCH_PATHS'] = aggregate_build_settings['FRAMEWORK_SEARCH_PATHS']
        build_configuration.build_settings['LIBRARY_SEARCH_PATHS'] = aggregate_build_settings['LIBRARY_SEARCH_PATHS']
      end
    end
  end
end

target 'flutter_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  flutter_pod 'flutter_module', :path => './debug/'
  # flutter_pod 'SoHuHost', '20230113.3.1.0.0'
  pod 'AFNetworking'
  pod 'SDWebImage'
  target 'flutter_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flutter_demoUITests' do
    # Pods for testing
  end
end
