# Uncomment the next line to define a global platform for your project
platform :ios, "9.0"
plugin "cocoapods-flutter"

# 开启module
use_frameworks! linkage: :static # 将组件已静态库的方式引入，使用后，会强制 use_modular_headers
use_modular_headers!

install! "cocoapods",
         deterministic_uuids: false,
         lock_pod_sources: false,
         disable_input_output_paths: true,
         generate_multiple_pod_projects: true, # 为每一个组件生成一个xcodeproj
         warn_for_unused_master_specs_repo: false,
         preserve_pod_file_structure: true # 保持目录结构不变

pre_install do |_installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

# pod install中间进行hook
post_install do |installer|
  # 设置默认配置
    installer.pods_project.targets.each do |target|
      # puts target.name
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'YES'
      end
    end

  # 通过脚本的方式，设置组件间的链接路径
  aggregate_target = installer.aggregate_targets[0]
  aggregate_build_settings_by_config = aggregate_target.xcconfigs.collect { |k, v| [k, v.to_hash] }.to_h
  # puts aggregate_build_settings_by_config
  installer.pod_target_subprojects.each do |pod_subproject|
    pod_subproject.native_targets.each do |pod_native_target|
      # puts pod_native_target
      pod_native_target.build_configurations.each do |build_configuration|
        aggregate_build_settings = aggregate_build_settings_by_config[build_configuration.name]
        build_configuration.build_settings["HEADER_SEARCH_PATHS"] = "${PODS_ROOT}/Headers/Public"
        build_configuration.build_settings["FRAMEWORK_SEARCH_PATHS"] =
          aggregate_build_settings["FRAMEWORK_SEARCH_PATHS"]
        build_configuration.build_settings["LIBRARY_SEARCH_PATHS"] = aggregate_build_settings["LIBRARY_SEARCH_PATHS"]
      end
    end
  end

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["CODE_SIGNING_ALLOWED"] = "NO"
      end
    end
  end
end

target "flutter_demo" do
  # Comment the next line if you don't want to use dynamic frameworks
  flutter_pod "sohu_mobile_flutter_host", path: "/Users/wf/sohu/code/"
  # flutter_pod 'SoHuHost', '20230208.3.1.0.1'
  #  flutter_pod 'flutter_module', :path => './debug/'


#   pod 'SnapKit'
#   pod 'ReachabilitySwift', '20211104.4.3.0.0'#, :binary => false
#   pod 'AFNetworking', '20211103.3.1.0.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']#,:binary => false
#   pod 'SnapKit'#, :binary => false
#   pod 'DeviceKit', '20211206.4.5.2.0'#, :binary => false

#   pod 'JPush'

#   # 网络层
#   pod 'SHMRequest'

#   # 崩溃统计相关
#   pod 'Bugly'

# #  # 搜狐埋点SDK
#   pod 'SHMUBSiOS', :git => 'git@code.sohuno.com:MPTC-iOS/SHMUBSiOS.git', :tag=>'0.9.0'

#   # 文件解压
#   pod 'SSZipArchive', :git => 'git@code.sohuno.com:MPTC-iOS/SSZipArchive.git', :branch=>'feature/shouso_version'#, :binary => false


#   pod 'SHJSBridge',:git =>'git@code.sohuno.com:MPTC-iOS/SHJSBridge.git',:branch=>'feature/base_1.1.0'

#   # 下发系统SDK
#   pod 'Jarvis', '1.0.1'#, :binary => false

#   # 弹框组件
#   pod 'MBProgressHUD', '20211103.1.1.0.0'#, :binary => false

#   # 异步绘制组件，网络原因，不自动更新
#   pod 'Texture', '20220825.3.1.0.0-beta'
# #  pod 'Texture', :path => '/Users/Annabelle/Desktop/工具组件/Texture', :tag => '20220823.3.1.0.0'
#   pod 'PINRemoteImage', :git=>'git@code.sohuno.com:MTPC_SH_THIRDMODULE/PINRemoteImage.git', :tag=>'3.0.3'
#   pod 'PINCache', :git=>'git@code.sohuno.com:MTPC_SH_THIRDMODULE/PINCache.git', :tag=>'3.0.3'
#   pod 'PINOperation', :git=>'git@code.sohuno.com:MTPC_SH_THIRDMODULE/PINOperation.git', :tag=>'1.2.1'
  

#   # 加密组件
#   pod 'CryptoSwift', '20211101.1.4.0.0'#, :binary => false

#   # 工具组件【cocoapods-binary插件bug，无法为附带bundle资源的组件生成framework】
#   # LoginKit里面有这个组件的全局依赖, 这边不用加也可以
#   pod 'SHNToolKit', '20220804.1.4.0.1'

#   # 网路组件
#   pod 'SBNNetwork', '20211103.1.0.8.0'#, :binary => false

#   # 分享组件
#   pod 'SHNShareKit', :git=>'git@code.sohuno.com:MTPC_SH_THIRDMODULE/SHNShareKit.git', :tag=>'20220428.0.0.7.0', :subspecs => ['core','shouso']

# # pod 'SHNRouter', :path=> "/Users/Annabelle/Desktop/工具组件/SHNRouter"

# #  pod 'SoHuHost',:git=>'git@code.sohuno.com:MOBILE-BASIC/SoHuHost.git',:tag=>'20220629.1.0.0.1'
# #  pod 'SHNRouter', '20220630.1.0.11.0', :subspecs => ['Core','Flutter']


#   pod 'WCDB', '20211207.1.0.8.2.0'

#   # 图片裁剪组件
#   pod 'RSKImageCropper', '20211214.1.6.3.0'

#   # 图片浏览器

#   pod 'KSPhotoBrowser' , :git=>'git@code.sohuno.com:MTPC_SH_THIRDMODULE/KSPhotoBrowser.git', :tag=> '20221206.0.3.1.2'

#   pod 'SHNRouter',:git=>'git@code.sohuno.com:MTPC_SH_THIRDMODULE/SHNRouter.git',:tag=>'20230105.1.0.20.0', :subspecs => ['Core','Flutter']


#   pod "AFNetworking"
  pod "SDWebImage", "5.15.2"
  # pod "SHMUBSiOS", git: "git@code.sohuno.com:MPTC-iOS/SHMUBSiOS.git", tag: "0.9.0"
end
